### ISSUE TITLE
Error:A problem occurred configuring project ':sample'.

### ISSUE THREAD

**Issue by 252162875** [Justson/AgentWebX5#1]
编译出这个错Error:A problem occurred configuring project ':sample'.

**Comment by huangying812** [comment]
我也遇到了，sample的build.config文件的问题，解决办法：删除
    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }
    sourceSets { main { assets.srcDirs = ['src/main/assets', 'src/main/assets/'] } }

**Comment by Justson** [comment]
楼上正解
