### ISSUE TITLE
是否封装了reload();方法

### ISSUE THREAD

**Issue by gaochunchun** [Justson/AgentWebX5#4]
您好，我引入了一个商城地址，在购物车中添加了商品后，点击删除----确认删除，该页面会重新刷新一遍，想知道是否提供了方法，如Tecent X5中的reload();方法，直接刷新页面的数据，而不是重新加载整个页面。期待您的回复，谢谢~

**Comment by Justson** [comment]
` mAgentWebX5.getLoader().reload();`
